// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Category struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Type      string         `json:"type"`
	Color     sql.NullString `json:"color"`
	Icon      sql.NullString `json:"icon"`
	ParentID  sql.NullString `json:"parent_id"`
	IsActive  sql.NullBool   `json:"is_active"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type PaymentMethod struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Transaction struct {
	ID                  string          `json:"id"`
	Type                string          `json:"type"`
	Description         string          `json:"description"`
	Amount              float64         `json:"amount"`
	TransactionDate     time.Time       `json:"transaction_date"`
	CategoryID          sql.NullString  `json:"category_id"`
	Tags                sql.NullString  `json:"tags"`
	CustomerVendor      sql.NullString  `json:"customer_vendor"`
	PaymentMethodID     sql.NullString  `json:"payment_method_id"`
	PaymentStatus       sql.NullString  `json:"payment_status"`
	ReferenceNumber     sql.NullString  `json:"reference_number"`
	InvoiceNumber       sql.NullString  `json:"invoice_number"`
	Notes               sql.NullString  `json:"notes"`
	Attachments         sql.NullString  `json:"attachments"`
	TaxAmount           sql.NullFloat64 `json:"tax_amount"`
	DiscountAmount      sql.NullFloat64 `json:"discount_amount"`
	NetAmount           sql.NullFloat64 `json:"net_amount"`
	Currency            sql.NullString  `json:"currency"`
	ExchangeRate        sql.NullFloat64 `json:"exchange_rate"`
	IsRecurring         sql.NullBool    `json:"is_recurring"`
	RecurringFrequency  sql.NullString  `json:"recurring_frequency"`
	RecurringEndDate    sql.NullTime    `json:"recurring_end_date"`
	ParentTransactionID sql.NullString  `json:"parent_transaction_id"`
	CreatedBy           string          `json:"created_by"`
	CreatedAt           sql.NullTime    `json:"created_at"`
	UpdatedAt           sql.NullTime    `json:"updated_at"`
	DeletedAt           sql.NullTime    `json:"deleted_at"`
}

type User struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Email       sql.NullString `json:"email"`
	Preferences sql.NullString `json:"preferences"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}
