// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountTransactions(ctx context.Context, arg CountTransactionsParams) (int64, error)
	CountTransactionsByCategory(ctx context.Context, categoryID sql.NullString) (int64, error)
	CountTransactionsByPaymentMethod(ctx context.Context, paymentMethodID sql.NullString) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (PaymentMethod, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	DeactivateCategory(ctx context.Context, id string) error
	DeactivatePaymentMethod(ctx context.Context, id string) error
	DeleteCategory(ctx context.Context, id string) error
	DeletePaymentMethod(ctx context.Context, id string) error
	DeleteTransaction(ctx context.Context, id string) error
	GetCategory(ctx context.Context, id string) (Category, error)
	GetCategoryByName(ctx context.Context, name string) (Category, error)
	GetCategoryName(ctx context.Context, id string) (string, error)
	GetCustomerVendorSuggestions(ctx context.Context, arg GetCustomerVendorSuggestionsParams) ([]GetCustomerVendorSuggestionsRow, error)
	GetDailyTransactionSummary(ctx context.Context, arg GetDailyTransactionSummaryParams) ([]GetDailyTransactionSummaryRow, error)
	GetDescriptionSuggestions(ctx context.Context, arg GetDescriptionSuggestionsParams) ([]GetDescriptionSuggestionsRow, error)
	GetMonthlyTrend(ctx context.Context, arg GetMonthlyTrendParams) ([]GetMonthlyTrendRow, error)
	GetPaymentMethod(ctx context.Context, id string) (PaymentMethod, error)
	GetPaymentMethodName(ctx context.Context, id string) (string, error)
	GetRecentTransactions(ctx context.Context, arg GetRecentTransactionsParams) ([]Transaction, error)
	GetTopCustomersVendors(ctx context.Context, arg GetTopCustomersVendorsParams) ([]GetTopCustomersVendorsRow, error)
	GetTransaction(ctx context.Context, id string) (Transaction, error)
	GetTransactionStats(ctx context.Context, arg GetTransactionStatsParams) (GetTransactionStatsRow, error)
	GetTransactionsByCategory(ctx context.Context, arg GetTransactionsByCategoryParams) ([]GetTransactionsByCategoryRow, error)
	ListActiveCategories(ctx context.Context) ([]Category, error)
	ListActivePaymentMethods(ctx context.Context) ([]PaymentMethod, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListCategoriesByType(ctx context.Context, type_ string) ([]Category, error)
	ListPaymentMethods(ctx context.Context) ([]PaymentMethod, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
	SearchTransactions(ctx context.Context, arg SearchTransactionsParams) ([]Transaction, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdatePaymentMethod(ctx context.Context, arg UpdatePaymentMethodParams) (PaymentMethod, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
}

var _ Querier = (*Queries)(nil)
