// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckCategoryDependencies(arg1) {
  return window['go']['main']['App']['CheckCategoryDependencies'](arg1);
}

export function CheckPaymentMethodDependencies(arg1) {
  return window['go']['main']['App']['CheckPaymentMethodDependencies'](arg1);
}

export function CreateCategory(arg1) {
  return window['go']['main']['App']['CreateCategory'](arg1);
}

export function CreatePaymentMethod(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePaymentMethod'](arg1, arg2, arg3);
}

export function CreateTransaction(arg1) {
  return window['go']['main']['App']['CreateTransaction'](arg1);
}

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function DeactivateCategory(arg1) {
  return window['go']['main']['App']['DeactivateCategory'](arg1);
}

export function DeactivatePaymentMethod(arg1) {
  return window['go']['main']['App']['DeactivatePaymentMethod'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeletePaymentMethod(arg1) {
  return window['go']['main']['App']['DeletePaymentMethod'](arg1);
}

export function DeleteTransaction(arg1) {
  return window['go']['main']['App']['DeleteTransaction'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function GetCategory(arg1) {
  return window['go']['main']['App']['GetCategory'](arg1);
}

export function GetPaymentMethod(arg1) {
  return window['go']['main']['App']['GetPaymentMethod'](arg1);
}

export function GetRecentTransactions(arg1) {
  return window['go']['main']['App']['GetRecentTransactions'](arg1);
}

export function GetTransaction(arg1) {
  return window['go']['main']['App']['GetTransaction'](arg1);
}

export function GetTransactionStats(arg1) {
  return window['go']['main']['App']['GetTransactionStats'](arg1);
}

export function GetTransactionsByCategory(arg1) {
  return window['go']['main']['App']['GetTransactionsByCategory'](arg1);
}

export function GetUser(arg1) {
  return window['go']['main']['App']['GetUser'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListActiveCategories() {
  return window['go']['main']['App']['ListActiveCategories']();
}

export function ListActivePaymentMethods() {
  return window['go']['main']['App']['ListActivePaymentMethods']();
}

export function ListCategories() {
  return window['go']['main']['App']['ListCategories']();
}

export function ListCategoriesByType(arg1) {
  return window['go']['main']['App']['ListCategoriesByType'](arg1);
}

export function ListPaymentMethods() {
  return window['go']['main']['App']['ListPaymentMethods']();
}

export function ListTransactions(arg1) {
  return window['go']['main']['App']['ListTransactions'](arg1);
}

export function SearchTransactions(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchTransactions'](arg1, arg2, arg3);
}

export function UpdateCategory(arg1, arg2) {
  return window['go']['main']['App']['UpdateCategory'](arg1, arg2);
}

export function UpdatePaymentMethod(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdatePaymentMethod'](arg1, arg2, arg3, arg4);
}

export function UpdateTransaction(arg1, arg2) {
  return window['go']['main']['App']['UpdateTransaction'](arg1, arg2);
}

export function UpdateUser(arg1, arg2) {
  return window['go']['main']['App']['UpdateUser'](arg1, arg2);
}
