// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {main} from '../models';
import {models} from '../models';

export function CheckCategoryDependencies(arg1:string):Promise<number>;

export function CheckPaymentMethodDependencies(arg1:string):Promise<number>;

export function CreateCategory(arg1:services.CreateCategoryParams):Promise<main.CategoryResponse>;

export function CreatePaymentMethod(arg1:string,arg2:string,arg3:boolean):Promise<main.PaymentMethodResponse>;

export function CreateTransaction(arg1:services.CreateTransactionParams):Promise<main.TransactionResponse>;

export function CreateUser(arg1:models.UserCreateRequest):Promise<models.User>;

export function DeactivateCategory(arg1:string):Promise<void>;

export function DeactivatePaymentMethod(arg1:string):Promise<void>;

export function DeleteCategory(arg1:string):Promise<void>;

export function DeletePaymentMethod(arg1:string):Promise<void>;

export function DeleteTransaction(arg1:string):Promise<void>;

export function DeleteUser(arg1:string):Promise<void>;

export function GetCategory(arg1:string):Promise<main.CategoryResponse>;

export function GetCustomerVendorSuggestions(arg1:string,arg2:string):Promise<Array<services.SuggestionItem>>;

export function GetDescriptionSuggestions(arg1:string,arg2:string):Promise<Array<services.SuggestionItem>>;

export function GetPaymentMethod(arg1:string):Promise<main.PaymentMethodResponse>;

export function GetRecentTransactions(arg1:number):Promise<Array<main.TransactionResponse>>;

export function GetTransaction(arg1:string):Promise<main.TransactionResponse>;

export function GetTransactionStats(arg1:services.StatsParams):Promise<main.TransactionStats>;

export function GetTransactionsByCategory(arg1:services.StatsParams):Promise<Array<main.CategorySummary>>;

export function GetUser(arg1:string):Promise<models.User>;

export function Greet(arg1:string):Promise<string>;

export function ListActiveCategories():Promise<Array<main.CategoryResponse>>;

export function ListActivePaymentMethods():Promise<Array<main.PaymentMethodResponse>>;

export function ListCategories():Promise<Array<main.CategoryResponse>>;

export function ListCategoriesByType(arg1:string):Promise<Array<main.CategoryResponse>>;

export function ListPaymentMethods():Promise<Array<main.PaymentMethodResponse>>;

export function ListTransactions(arg1:services.ListTransactionParams):Promise<Array<main.TransactionResponse>>;

export function SearchTransactions(arg1:string,arg2:number,arg3:number):Promise<Array<main.TransactionResponse>>;

export function UpdateCategory(arg1:string,arg2:services.UpdateCategoryParams):Promise<main.CategoryResponse>;

export function UpdatePaymentMethod(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<main.PaymentMethodResponse>;

export function UpdateTransaction(arg1:string,arg2:services.UpdateTransactionParams):Promise<main.TransactionResponse>;

export function UpdateUser(arg1:string,arg2:models.UserUpdateRequest):Promise<models.User>;
